{{- if .Values.ingress.enabled -}}
{{- $fullName := include "desk.fullname" . -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "desk.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    {{- if .Values.ingress.host }}
    - secretName: {{ $fullName }}-tls
      hosts:
        - {{ .Values.ingress.host | quote }}
    {{- end }}
    {{- range .Values.ingress.tls.additional }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "desk.frontend.fullname" . }}
                port:
                  number: {{ .Values.frontend.service.port }}
              {{- else }}
              serviceName: {{ include "desk.frontend.fullname" . }}
              servicePort: {{ .Values.frontend.service.port }}
            {{- end }}
          - path: /api
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "desk.backend.fullname" . }}
                port:
                  number: {{ .Values.backend.service.port }}
              {{- else }}
              serviceName: {{ include "desk.backend.fullname" . }}
              servicePort: {{ .Values.backend.service.port }}
            {{- end }}
          {{- with .Values.ingress.customBackends }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
    {{- end }}
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $.Values.ingress.path | quote }}
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "desk.frontend.fullname" $ }}
                port:
                  number: {{ $.Values.frontend.service.port }}
              {{- else }}
              serviceName: {{ include "desk.frontend.fullname" $ }}
              servicePort: {{ $.Values.frontend.service.port }}
            {{- end }}
          - path: /api
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "desk.backend.fullname" $ }}
                port:
                  number: {{ $.Values.backend.service.port }}
              {{- else }}
              serviceName: {{ include "desk.backend.fullname" $ }}
              servicePort: {{ $.Values.backend.service.port }}
            {{- end }}
          {{- with $.Values.ingress.customBackends }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
    {{- end }}
{{- end }}

